vich_uploader:
    db_driver: orm
    metadata:         
        type: attribute

    mappings:
        portfolio:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'

